### ISSUE TITLE
KeyError in full_preprocessing

### ISSUE THREAD

**Issue by Qhan-Hu** [AI4HealthUOL/ECG-MIMIC#5]
Hi, thanks for your reply. I have fixed that problem. 

However, I met another error when executing till line 210 of 'full_preprocessing.py'. It seems that the key of variable 'df' is wrongly defined, as below.
![image](https://github.com/user-attachments/assets/f5ac6202-c63c-4962-a8e1-6b2929684451)

**Comment by juanlopezcode** [comment]
it seems that your line 125 reads that you already have a records_w_diag.pkl, my believe is that your final part of step 2 saved a records_w_diag.pkl file and after it broke (last issue) and now, since it is available, line 127 loads it and is missing several columns that are not being computed in the else statement in line 128. I would suggest you delete your records_w_diag.pkl and start the processing once again from the start, hope it helps

Juan
